name: SafeDep vet
description:
  Run vet as a GitHub Action to vet your dependencies against OSS Supply Chain
  attacks. Performs incremental vetting of changed dependencies in a pull
  request.
author: 'SafeDep'

branding:
  icon: 'git-pull-request'
  color: 'red'

inputs:
  policy:
    description: Path to policy file, default policy will be used when not given
    required: false
  cloud:
    description: Synchronize configuration, policy and report with SafeDep cloud
    required: false
    default: false
  cloud-key:
    description: API key to use for synchronizing report with SafeDep cloud
    required: false
  version:
    description:
      vet version to use for the scan. Defaults to using latest release
    required: false

outputs:
  report:
    description: Path to SARIF report for uploading to Github Security tab

runs:
  using: node20
  main: dist/index.js
