name: SafeDep vet
description: Run vet as a GitHub Action to vet your dependencies against common OSS Supply Chain attacks
author: 'Your name or organization here'

branding:
  icon: 'git-pull-request'
  color: 'red'

inputs:
  api-key:
    description: API key to use for synchronizing report with SafeDep cloud
    required: false
  policy:
    description: Path to policy file
    required: false
  cloud:
    description: Synchronize configuration, policy and report with SafeDep cloud
    required: false
    default: false

outputs:
  report:
    description: Path to SARIF report for uploading to Github Security tab

runs:
  using: node20
  main: dist/index.js
