name: Lint Codebase

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Check formatting
        id: check-formatting
        run: npm run format:check

      - name: Check eslint
        id: check-eslint
        run: npm run lint

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7.3.0

        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: (dist|__tests__)/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: tsconfig.json
          VALIDATE_BASH: false
          VALIDATE_JSCPD: false
